# Generated by Django 4.2.1 on 2023-07-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feelflowapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='emotions',
            field=models.CharField(choices=[('p', 'positif'), ('n', 'negatif')], default='p', max_length=20),
        ),
    ]
