# Generated by Django 4.2.1 on 2023-07-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feelflowapp', '0002_message_emotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='emotions',
            field=models.CharField(choices=[('p', 'positif'), ('n', 'negatif')], default='p', max_length=50),
        ),
    ]
